(load "/Users/Endy Iskandar Imam/Documents/SCHOOL/Senior Fall 2018/CS450/cs450-bootstrap.scm")

(compiler)
example/00-five.scm
(compiler)
example/01-define.scm
(compiler)
example/02-define2.scm
(compiler)
example/03-if.scm
(compiler)
example/04-lambda.scm
(compiler)
example/05-plus.scm
(compiler)
example/06-define3.scm
(compiler)
example/07-define4.scm
(compiler)
example/08-application.scm

(run-machine)
example/00-five.cmp
(run-machine)
example/01-define.cmp
(run-machine)
example/02-define2.cmp
(run-machine)
example/03-if.cmp
(run-machine)
example/04-lambda.cmp
(run-machine)
example/05-plus.cmp
(run-machine)
example/06-define3.cmp
(run-machine)
example/07-define4.cmp
(run-machine)
example/08-application.cmp
